name: Deploy to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "alisaqibh1@gmail.com"
          git config user.name "alisaqib14"
          git remote add hf https://alisaqib14:$HF_TOKEN@huggingface.co/spaces/alisaqib14/skinsense-ai-backend
          git push hf main --force
